version: '2.2'

services:
  # NestJS Backend
  backend:
    container_name: backend
    build:
      context: ./Code
    env_file:
      - .env.production
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - photogo-network

  # PostgreSQL với pg_cron
  postgres:
    build:
      context: ./DB
    image: pgsql_with_cron
    container_name: pgsql_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234554321
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - photogo-network

networks:
  photogo-network:
    driver: bridge

volumes:
  pgdata:
