version: '3'

services:
  # NestJS Backend
  backend:
    container_name: backend
    build:
      context: ./Code
    env_file:
      - .env.production
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - photogo-network

  # PostgreSQL với pg_cron
  postgres:
    build:
      context: ./DB
    image: pgsql_with_cron
    container_name: pgsql_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234554321
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - photogo-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  photogo-network:
    external: true

volumes:
  pgdata:
