name: Deploy to VPS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies & Build NestJS
        run: |
          npm install
          npm run build

      - name: Prepare Code folder to send
        run: |
          mkdir -p .github/temp_build/Code
          cp -r dist package-lock.json package.json .github/temp_build/Code/
          cp docker-compose.yml .github/temp_build/

      - name: Copy Code to VPS
        run: |
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          # Tạo thư mục đích trên VPS
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            mkdir -p /home/root/backend/Code &&
            rm -rf /home/root/backend/Code/dist  # Xóa thư mục dist trước khi copy
          "
          # Copy dist, package-lock.json, package.json vào /home/root/backend/Code
          scp -o StrictHostKeyChecking=no -i private_key.pem -r .github/temp_build/Code/* ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/root/backend/Code
          # Copy docker-compose.yml vào /home/root/backend
          scp -o StrictHostKeyChecking=no -i private_key.pem .github/temp_build/docker-compose.yml ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/root/backend/
          rm -f private_key.pem

      - name: SSH and restart backend
        run: |
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd /home/root/backend &&
            docker-compose down &&
            docker-compose up -d --build
          "
          rm -f private_key.pem
        env:
          VPS_PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
