name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies & Build NestJS
        run: |
          npm install
          npm run build

      - name: Prepare Code folder to send
        run: |
          mkdir -p .github/temp_build/Code
          cp -r dist package*.json tsconfig.json Dockerfile .github/temp_build/Code/

      - name: Copy Code to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          source: ".github/temp_build/"
          target: "/home/root/backend"

      - name: SSH and restart backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd /home/root/backend
            docker compose down
            docker compose up --build -d
