name: Deploy NestJS to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build NestJS
        run: npm run build

      - name: Prepare app folder for deployment
        run: |
          mkdir -p deploy_folder
          cp -r dist package*.json tsconfig.json docker-compose.yml Dockerfile deploy_folder/

      - name: Save private key
        run: |
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Copy files to VPS
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" deploy_folder/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/backend

      - name: SSH into VPS and restart Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/backend
            docker compose down
            docker compose up --build -d
